### ISSUE TITLE
Cannot Load Dnn.Modules.Newsletters.Newsletter

### ISSUE THREAD

**Issue by HZass** [DNNCommunity/DNN.Newsletter#25]
Cannot load newletters module as shown in the following report:
ModuleId:780

ModuleDefId:165

FriendlyName:Send email messages to users, security roles and specific email addresses

ModuleControlSource:DesktopModules/Admin/Newsletters/Newsletter.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:d7d7a04a-aa1a-4710-ab0e-aeac9990577a

AssemblyVersion:9.4.4

PortalId:0

UserId:2

TabId:246

RawUrl:/Admin/Newsletters

Referrer:http://vwcprod.azurewebsites.net/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=325

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edg/83.0.478.50

ExceptionHash:EV52dX0bdmeHQ7FzKGlKLOesmCo=

Message:Could not load type 'Dnn.Modules.Newsletters.Newsletter'.

StackTrace:

InnerMessage:Could not load type 'Dnn.Modules.Newsletters.Newsletter'.

InnerStackTrace:

   at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding)
   at System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath)
   at System.Web.UI.TemplateParser.ParseInternal()
   at System.Web.UI.TemplateParser.Parse()
   at System.Web.Compilation.BaseTemplateBuildProvider.get_CodeCompilerType()
   at System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider)
   at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc)
   at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateControl(TemplateControl containerControl, String controlKey, String controlSrc)
   at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration)
   at DotNetNuke.ModulePipeline.ModuleControlPipeline.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration)
   at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: RD0003FF68F3EF

## Software Versions
- DNN: 09.04.00
- Module: 08.00.01

## To Reproduce
1. Go to Administration/Newsletters
2. See error

## Expected behavior
Expect to see panel to collect information relating to newsletters.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by HZass** [comment]
Reinstalled release 08.00.01 and it appears as if all is okay.  I am closing this issue.
